import type { LinkedInJob } from '@/types'

export const DUMMY_LINKEDIN_JOBS: LinkedInJob[] = [
  {
    id: 'job-001',
    title: 'Senior Software Engineer',
    organization: 'Google',
    organization_url: 'https://www.linkedin.com/company/google',
    organization_logo: 'https://logo.clearbit.com/google.com',
    date_posted: new Date(Date.now() - 1 * 86_400_000).toISOString(),
    date_created: new Date(Date.now() - 1 * 86_400_000).toISOString(),
    date_validthrough: null,
    url: 'https://careers.google.com',
    external_apply_url: 'https://careers.google.com/apply/001',
    source: 'linkedin',
    source_type: 'linkedin',
    source_domain: 'linkedin.com',
    seniority: 'Mid-Senior level',
    directapply: true,
    employment_type: ['FULL_TIME'],
    remote_derived: false,
    location_type: 'On-site',
    location_requirements_raw: null,
    locations_raw: [
      {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Mountain View',
          addressRegion: 'CA',
          addressCountry: 'US',
        },
      },
    ],
    locations_derived: ['Mountain View, CA, United States'],
    cities_derived: ['Mountain View'],
    counties_derived: ['Santa Clara County'],
    regions_derived: ['California'],
    countries_derived: ['United States'],
    timezones_derived: ['America/Los_Angeles'],
    lats_derived: [37.3861],
    lngs_derived: [-122.0839],
    salary_raw: {
      '@type': 'MonetaryAmount',
      currency: 'USD',
      value: { '@type': 'QuantitativeValue', minValue: 160000, maxValue: 220000, unitText: 'YEAR' },
    },
    linkedin_org_employees: 180000,
    linkedin_org_url: 'https://www.linkedin.com/company/google',
    linkedin_org_size: '10001+',
    linkedin_org_slogan: 'Don\'t be evil',
    linkedin_org_industry: 'Internet',
    linkedin_org_followers: 30000000,
    linkedin_org_headquarters: 'Mountain View, CA',
    linkedin_org_type: 'Public Company',
    linkedin_org_foundeddate: '1998',
    linkedin_org_specialties: ['Search', 'Cloud Computing', 'AI', 'Android', 'YouTube'],
    linkedin_org_locations: ['Mountain View, CA', 'New York, NY', 'London, UK'],
    linkedin_org_description: 'Google LLC is an American multinational technology company focusing on artificial intelligence, online advertising, search engine technology, cloud computing, computer software, quantum computing, e-commerce, and consumer electronics.',
    linkedin_org_recruitment_agency_derived: false,
    linkedin_org_slug: 'google',
    no_jb_schema: false,
    ats_duplicate: false,
    description_text: `We are looking for a Senior Software Engineer to join our team at Google. You will design, develop, and maintain large-scale distributed systems.\n\nResponsibilities:\n- Design, implement, and ship scalable software solutions\n- Collaborate with cross-functional teams\n- Mentor junior engineers\n- Participate in code reviews\n\nRequirements:\n- 5+ years of software engineering experience\n- Strong proficiency in Python, Go, or Java\n- Experience with distributed systems\n- BS/MS in Computer Science or equivalent`,
  },
  {
    id: 'job-002',
    title: 'Frontend Engineer',
    organization: 'Meta',
    organization_url: 'https://www.linkedin.com/company/meta',
    organization_logo: 'https://logo.clearbit.com/meta.com',
    date_posted: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    date_created: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    date_validthrough: null,
    url: 'https://metacareers.com',
    external_apply_url: null,
    source: 'linkedin',
    source_type: 'linkedin',
    source_domain: 'linkedin.com',
    seniority: 'Mid-Senior level',
    directapply: false,
    employment_type: ['FULL_TIME'],
    remote_derived: true,
    location_type: 'Remote',
    location_requirements_raw: null,
    locations_raw: [
      {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          addressLocality: null,
          addressRegion: null,
          addressCountry: 'US',
        },
      },
    ],
    locations_derived: ['Remote, United States'],
    cities_derived: null,
    counties_derived: null,
    regions_derived: null,
    countries_derived: ['United States'],
    timezones_derived: ['America/New_York'],
    lats_derived: [],
    lngs_derived: [],
    salary_raw: {
      '@type': 'MonetaryAmount',
      currency: 'USD',
      value: { '@type': 'QuantitativeValue', minValue: 140000, maxValue: 190000, unitText: 'YEAR' },
    },
    linkedin_org_employees: 77000,
    linkedin_org_url: 'https://www.linkedin.com/company/meta',
    linkedin_org_size: '10001+',
    linkedin_org_slogan: 'Move fast.',
    linkedin_org_industry: 'Technology',
    linkedin_org_followers: 12000000,
    linkedin_org_headquarters: 'Menlo Park, CA',
    linkedin_org_type: 'Public Company',
    linkedin_org_foundeddate: '2004',
    linkedin_org_specialties: ['Social Media', 'VR', 'AR', 'AI', 'Advertising'],
    linkedin_org_locations: ['Menlo Park, CA', 'New York, NY', 'London, UK'],
    linkedin_org_description: 'Meta builds technologies that help people connect, find communities, and grow businesses.',
    linkedin_org_recruitment_agency_derived: false,
    linkedin_org_slug: 'meta',
    no_jb_schema: false,
    ats_duplicate: false,
    description_text: `Meta is looking for a Frontend Engineer to help build the next generation of social experiences.\n\nResponsibilities:\n- Build high-quality React components\n- Optimize performance for millions of users\n- Work with design systems\n\nRequirements:\n- 4+ years of frontend experience\n- Expert-level React & TypeScript\n- Experience with GraphQL\n- Strong CSS skills`,
  },
  {
    id: 'job-003',
    title: 'Data Engineer Intern',
    organization: 'Microsoft',
    organization_url: 'https://www.linkedin.com/company/microsoft',
    organization_logo: 'https://logo.clearbit.com/microsoft.com',
    date_posted: new Date(Date.now() - 5 * 86_400_000).toISOString(),
    date_created: new Date(Date.now() - 5 * 86_400_000).toISOString(),
    date_validthrough: null,
    url: 'https://careers.microsoft.com',
    external_apply_url: 'https://careers.microsoft.com/apply/003',
    source: 'linkedin',
    source_type: 'linkedin',
    source_domain: 'linkedin.com',
    seniority: 'Entry level',
    directapply: true,
    employment_type: ['INTERNSHIP'],
    remote_derived: false,
    location_type: 'On-site',
    location_requirements_raw: null,
    locations_raw: [
      {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Redmond',
          addressRegion: 'WA',
          addressCountry: 'US',
        },
      },
    ],
    locations_derived: ['Redmond, WA, United States'],
    cities_derived: ['Redmond'],
    counties_derived: ['King County'],
    regions_derived: ['Washington'],
    countries_derived: ['United States'],
    timezones_derived: ['America/Los_Angeles'],
    lats_derived: [47.6740],
    lngs_derived: [-122.1215],
    salary_raw: {
      '@type': 'MonetaryAmount',
      currency: 'USD',
      value: { '@type': 'QuantitativeValue', minValue: 7000, maxValue: 9000, unitText: 'MONTH' },
    },
    linkedin_org_employees: 220000,
    linkedin_org_url: 'https://www.linkedin.com/company/microsoft',
    linkedin_org_size: '10001+',
    linkedin_org_slogan: 'Empower every person and organization',
    linkedin_org_industry: 'Computer Software',
    linkedin_org_followers: 20000000,
    linkedin_org_headquarters: 'Redmond, WA',
    linkedin_org_type: 'Public Company',
    linkedin_org_foundeddate: '1975',
    linkedin_org_specialties: ['Cloud', 'AI', 'Azure', 'Office 365', 'Gaming'],
    linkedin_org_locations: ['Redmond, WA', 'San Francisco, CA', 'London, UK'],
    linkedin_org_description: 'Microsoft enables digital transformation for the era of an intelligent cloud and an intelligent edge.',
    linkedin_org_recruitment_agency_derived: false,
    linkedin_org_slug: 'microsoft',
    no_jb_schema: false,
    ats_duplicate: false,
    description_text: `Join Microsoft as a Data Engineering Intern and work on real-world data pipelines powering Azure services.\n\nResponsibilities:\n- Build and maintain ETL pipelines\n- Work with large-scale datasets on Azure\n- Collaborate with senior engineers\n\nRequirements:\n- Currently pursuing BS/MS in CS or Data Science\n- Familiarity with Python and SQL\n- Interest in cloud technologies`,
  },
  {
    id: 'job-004',
    title: 'ML Engineer',
    organization: 'OpenAI',
    organization_url: 'https://www.linkedin.com/company/openai',
    organization_logo: 'https://logo.clearbit.com/openai.com',
    date_posted: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    date_created: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    date_validthrough: null,
    url: 'https://openai.com/careers',
    external_apply_url: null,
    source: 'linkedin',
    source_type: 'linkedin',
    source_domain: 'linkedin.com',
    seniority: 'Mid-Senior level',
    directapply: false,
    employment_type: ['FULL_TIME'],
    remote_derived: true,
    location_type: 'Hybrid',
    location_requirements_raw: null,
    locations_raw: [
      {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'San Francisco',
          addressRegion: 'CA',
          addressCountry: 'US',
        },
      },
    ],
    locations_derived: ['San Francisco, CA, United States'],
    cities_derived: ['San Francisco'],
    counties_derived: ['San Francisco County'],
    regions_derived: ['California'],
    countries_derived: ['United States'],
    timezones_derived: ['America/Los_Angeles'],
    lats_derived: [37.7749],
    lngs_derived: [-122.4194],
    salary_raw: {
      '@type': 'MonetaryAmount',
      currency: 'USD',
      value: { '@type': 'QuantitativeValue', minValue: 200000, maxValue: 300000, unitText: 'YEAR' },
    },
    linkedin_org_employees: 770,
    linkedin_org_url: 'https://www.linkedin.com/company/openai',
    linkedin_org_size: '501-1000',
    linkedin_org_slogan: 'Creating safe AGI for humanity',
    linkedin_org_industry: 'Research',
    linkedin_org_followers: 5000000,
    linkedin_org_headquarters: 'San Francisco, CA',
    linkedin_org_type: 'Privately Held',
    linkedin_org_foundeddate: '2015',
    linkedin_org_specialties: ['AI', 'Machine Learning', 'NLP', 'Computer Vision'],
    linkedin_org_locations: ['San Francisco, CA'],
    linkedin_org_description: 'OpenAI is an AI research company. Our mission is to ensure that artificial general intelligence benefits all of humanity.',
    linkedin_org_recruitment_agency_derived: false,
    linkedin_org_slug: 'openai',
    no_jb_schema: false,
    ats_duplicate: false,
    description_text: `We are looking for ML Engineers passionate about pushing the boundaries of AI.\n\nResponsibilities:\n- Train and fine-tune large language models\n- Develop scalable ML infrastructure\n- Research novel training techniques\n\nRequirements:\n- Strong background in deep learning\n- Experience with PyTorch\n- Understanding of transformers and LLMs\n- MS or PhD in ML/CS preferred`,
  },
  {
    id: 'job-005',
    title: 'DevOps Engineer',
    organization: 'Stripe',
    organization_url: 'https://www.linkedin.com/company/stripe',
    organization_logo: 'https://logo.clearbit.com/stripe.com',
    date_posted: new Date(Date.now() - 7 * 86_400_000).toISOString(),
    date_created: new Date(Date.now() - 7 * 86_400_000).toISOString(),
    date_validthrough: null,
    url: 'https://stripe.com/jobs',
    external_apply_url: 'https://stripe.com/jobs/apply/005',
    source: 'linkedin',
    source_type: 'linkedin',
    source_domain: 'linkedin.com',
    seniority: 'Mid-Senior level',
    directapply: true,
    employment_type: ['FULL_TIME'],
    remote_derived: true,
    location_type: 'Remote',
    location_requirements_raw: null,
    locations_raw: [
      {
        '@type': 'Place',
        address: { '@type': 'PostalAddress', addressLocality: null, addressRegion: null, addressCountry: 'US' },
      },
    ],
    locations_derived: ['Remote'],
    cities_derived: null,
    counties_derived: null,
    regions_derived: null,
    countries_derived: ['United States'],
    timezones_derived: [],
    lats_derived: [],
    lngs_derived: [],
    salary_raw: {
      '@type': 'MonetaryAmount',
      currency: 'USD',
      value: { '@type': 'QuantitativeValue', minValue: 150000, maxValue: 200000, unitText: 'YEAR' },
    },
    linkedin_org_employees: 8000,
    linkedin_org_url: 'https://www.linkedin.com/company/stripe',
    linkedin_org_size: '5001-10000',
    linkedin_org_slogan: 'Increase the GDP of the internet',
    linkedin_org_industry: 'Financial Services',
    linkedin_org_followers: 2000000,
    linkedin_org_headquarters: 'San Francisco, CA',
    linkedin_org_type: 'Privately Held',
    linkedin_org_foundeddate: '2010',
    linkedin_org_specialties: ['Payments', 'FinTech', 'APIs', 'Developer Tools'],
    linkedin_org_locations: ['San Francisco, CA', 'Dublin, Ireland', 'London, UK'],
    linkedin_org_description: 'Stripe is a technology company that builds economic infrastructure for the internet.',
    linkedin_org_recruitment_agency_derived: false,
    linkedin_org_slug: 'stripe',
    no_jb_schema: false,
    ats_duplicate: false,
    description_text: `Stripe is looking for a DevOps Engineer to help scale our infrastructure to support millions of businesses worldwide.\n\nResponsibilities:\n- Manage Kubernetes clusters and CI/CD pipelines\n- Ensure 99.99% uptime for payment infrastructure\n- Automate operational tasks\n\nRequirements:\n- 4+ years of DevOps/SRE experience\n- Kubernetes, Terraform, AWS/GCP\n- Strong scripting skills (Python, Bash)\n- Experience with observability tools`,
  },
]
